# Generated by Django 5.2.4 on 2026-09-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_sex', models.CharField(blank=True, max_length=10, null=True)),
                ('model_type', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='scans/')),
                ('diagnosis_status', models.CharField(blank=True, max_length=255)),
                ('detailed_report', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
